name: Python CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov
        pip install -r structured/requirements.txt
        cd structured
        pip install -e ./

    - name: Run Pytest with coverage
      run: |
        pytest --cov=src --cov-report=term --cov-report=xml --cov-fail-under=80
